#!/usr/bin/env python3
"""arch_map.py — auto-generates ARCHITECTURE.md, a data-dependency map of the pack tooling.

Why (2026-07-09): ~30 standalone scripts now funnel every path/id through packenv.py
(`import packenv as E`; see packenv.py docstring for the "why"). Nobody can see at a glance what
depends on what without reading 30 files. This statically parses every *.py in this directory with
the `ast` module (never imports/executes them — several scripts do work at import time or hit the
network) and emits a Mermaid flowchart (script->script imports, script->packenv-data-artifact uses)
plus an overview table into ARCHITECTURE.md. Re-runnable: it regenerates from source, so the map
never goes stale — run it after adding/removing a script or a packenv key.

Usage:
    python3 arch_map.py            # write ARCHITECTURE.md (+ ARCHITECTURE.dot)
    python3 arch_map.py --check    # exit 1 if ARCHITECTURE.md is stale vs source (CI/preflight gate)
"""
import argparse
import ast
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SELF_NAME = os.path.basename(__file__)
OUTPUT_MD = os.path.join(HERE, "ARCHITECTURE.md")
OUTPUT_DOT = os.path.join(HERE, "ARCHITECTURE.dot")

GENERATED_NOTE = (
    "> Auto-generated by `arch_map.py` from a static AST scan of the *.py files in this directory — "
    "do NOT hand-edit. Re-run `python3 arch_map.py` after adding/removing a script or a packenv key."
)

# ── packenv key -> real-world data artifact ─────────────────────────────────────────────────────
# Ordered rules, first regex match on the packenv attribute name wins. Any key that matches nothing
# falls into a per-key catch-all bucket (ART_OTHER_<key>) so a new/renamed packenv key never gets
# silently dropped from the map — it just shows up ungrouped until this table is taught about it.
ARTIFACT_RULES = [
    (re.compile(r"^CURSE_BUNDLE$"), "ART_CURSE_BUNDLE", "curse.bundle.json"),
    (re.compile(r"^URL_BUNDLE$"), "ART_URL_BUNDLE", "url.bundle.json"),
    (re.compile(r"^MODRINTH_BUNDLE$"), "ART_MODRINTH_BUNDLE", "modrinth.bundle.json"),
    (re.compile(r"^RELEASE_MANIFEST$"), "ART_RELEASE_MANIFEST", "release-manifest.json"),
    (re.compile(r"^REPOS_JSON$"), "ART_REPOS_JSON", "repos.json"),
    (re.compile(r"^CLIENT_MANIFEST$"), "ART_CLIENT_MANIFEST", "client manifest.json"),
    (re.compile(r"^INSTANCE_TEST"), "ART_INSTANCE_TEST", "TEST client instance"),
    (re.compile(r"^INSTANCE_SERVER"), "ART_INSTANCE_SERVER", "SERVER instance"),
    (re.compile(r"^INSTANCES_ROOT$"), "ART_INSTANCES_ROOT", "instances root dir"),
    (
        re.compile(r"^(PACK_DIR|PACK_REPO|PACK_NAME|PACK_PROJECT_ID|SRC_COMMON|CANONICAL_CONFIG"
                    r"|MOD_DIRECTOR|SERVER_SRC|SERVER_MODS|CLIENT_SRC)$"),
        "ART_PACK_DIR", "pack repo (PACK_DIR family)",
    ),
    (re.compile(r"^(HUB|GITHUB_ROOT|HOME)$"), "ART_HUB", "Mod-Sandbox hub root"),
    (re.compile(r"^(cf_api_key|CF_API_KEY)$"), "ART_SECRETS", ".env secrets (CF/Modrinth tokens)"),
    (re.compile(r"^(cf_upload_token|CF_UPLOAD_TOKEN)$"), "ART_SECRETS", ".env secrets (CF/Modrinth tokens)"),
    (re.compile(r"^(modrinth_token|MODRINTH_TOKEN)$"), "ART_SECRETS", ".env secrets (CF/Modrinth tokens)"),
]

# Secret env-var names some legacy scripts read directly via os.environ, bypassing packenv's
# cf_api_key()/cf_upload_token()/modrinth_token() helpers. Surfacing this is itself a useful finding
# (these scripts predate the packenv refactor and were never migrated).
DIRECT_SECRET_NAMES = ("CF_API_KEY", "CF_UPLOAD_TOKEN", "MODRINTH_TOKEN")

# Lightweight external-tool touches, detected via AST as a list/tuple-literal first element (covers
# both `subprocess.run(["git", ...])` and `cmd = ["gh", ...]; subprocess.run(cmd)`). AST-based (not a
# regex over raw source) so a script whose *code* merely mentions these tool names in a string/comment
# — e.g. this very script's own pattern table — is never mistaken for a real subprocess call.
EXTERNAL_TOOL_FIRST_ELEMENTS = {
    "git": "git",
    "gh": "gh",
    "gradle": "gradlew",  # matches both "gradlew" and "./gradlew" (checked via endswith below)
}

# Light, best-effort script clustering by filename keyword. Order matters (first match wins).
# Intentionally shallow — correctness of the dependency edges matters far more than pretty grouping.
CLUSTER_RULES = [
    ("changelog", "CLUSTER_CHANGELOG", "Changelog"),
    ("bundle", "CLUSTER_BUNDLE", "Bundle / mod-director"),
    ("release", "CLUSTER_RELEASE", "Release"),
    ("upload", "CLUSTER_RELEASE", "Release"),
    ("instance", "CLUSTER_INSTANCE", "Instance tools"),
]


def artifact_for_key(key):
    for pattern, art_id, label in ARTIFACT_RULES:
        if pattern.match(key):
            return art_id, label
    return "ART_OTHER_" + re.sub(r"[^A-Za-z0-9_]", "_", key), f"packenv.{key} (unclassified)"


def sanitize_id(name):
    """Mermaid/DOT node ids must be alnum/underscore only — no dots, dashes, spaces, '!'."""
    out = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if out and out[0].isdigit():
        out = "_" + out
    return out


class ScriptInfo:
    def __init__(self, filename):
        self.filename = filename
        self.stem = filename[:-3] if filename.endswith(".py") else filename
        self.node_id = "S_" + sanitize_id(self.stem)
        self.purpose = "(no module docstring)"
        self.local_imports = set()   # other local script stems this one imports
        self.data_keys = set()       # raw packenv key / helper names referenced
        self.external_tags = set()   # 'git' / 'gh' / 'gradle'
        self.parse_error = None

    @property
    def data_artifacts(self):
        return sorted({artifact_for_key(k) for k in self.data_keys}, key=lambda t: t[1])


def first_sentence(docstring, stem, max_len=100):
    if not docstring:
        return "(no module docstring)"
    # Drop a leading "<stem>.py — " / "<stem>.py -- " self-reference; the table already names the script.
    text = re.sub(rf"^\s*{re.escape(stem)}\.py\s*[—\-–]+\s*", "", docstring.strip())
    first_para = text.split("\n\n", 1)[0].replace("\n", " ")
    first_para = re.sub(r"\s+", " ", first_para).strip()
    m = re.match(r"^(.*?[.!?])(\s|$)", first_para)
    sentence = m.group(1) if m else first_para
    if len(sentence) > max_len:
        sentence = sentence[: max_len - 1].rstrip() + "…"
    return sentence or "(no module docstring)"


def collect_scripts():
    filenames = sorted(
        f for f in os.listdir(HERE)
        if f.endswith(".py") and os.path.isfile(os.path.join(HERE, f))
    )
    # Only files with a valid Python identifier stem can be the target of `import <stem>` — e.g.
    # "!installdependencies.py" cannot be imported by ordinary syntax, so it's excluded from the
    # match-pool (but still scanned and shown as a node/table row).
    local_module_names = {
        f[:-3] for f in filenames if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", f[:-3])
    }

    infos = []
    for filename in filenames:
        info = ScriptInfo(filename)
        path = os.path.join(HERE, filename)
        try:
            with open(path, encoding="utf-8") as fh:
                src = fh.read()
        except OSError as e:
            info.parse_error = str(e)
            info.purpose = f"(unreadable: {e})"
            infos.append(info)
            continue

        try:
            tree = ast.parse(src, filename=filename)
        except SyntaxError as e:
            info.parse_error = str(e)
            info.purpose = f"(failed to parse: {e})"
            infos.append(info)
            continue

        info.purpose = first_sentence(ast.get_docstring(tree), info.stem)

        packenv_alias = None
        direct_names = {}  # bare name in this module -> packenv key it stands for
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    top = alias.name.split(".")[0]
                    if top == "packenv":
                        packenv_alias = alias.asname or "packenv"
                    elif top in local_module_names and top != info.stem:
                        info.local_imports.add(top)
            elif isinstance(node, ast.ImportFrom):
                if node.module == "packenv":
                    for alias in node.names:
                        direct_names[alias.asname or alias.name] = alias.name
                elif node.module and node.module.split(".")[0] in local_module_names \
                        and node.module.split(".")[0] != info.stem:
                    info.local_imports.add(node.module.split(".")[0])

        uses_os_environ = False
        for node in ast.walk(tree):
            if isinstance(node, ast.Attribute) and isinstance(node.value, ast.Name) \
                    and packenv_alias and node.value.id == packenv_alias:
                info.data_keys.add(node.attr)
            elif isinstance(node, ast.Name) and node.id in direct_names:
                info.data_keys.add(direct_names[node.id])
            elif isinstance(node, ast.Attribute) and node.attr == "environ" \
                    and isinstance(node.value, ast.Name) and node.value.id == "os":
                uses_os_environ = True
            elif isinstance(node, (ast.List, ast.Tuple)) and node.elts:
                first = node.elts[0]
                if isinstance(first, ast.Constant) and isinstance(first.value, str):
                    for tag, prefix in EXTERNAL_TOOL_FIRST_ELEMENTS.items():
                        if first.value == prefix or first.value.endswith("/" + prefix):
                            info.external_tags.add(tag)
            elif isinstance(node, ast.Constant) and isinstance(node.value, str) \
                    and node.value in DIRECT_SECRET_NAMES:
                # Direct os.environ secret reads that bypass packenv's cf_api_key()/etc helpers
                # (legacy pre-refactor scripts). Only counts if the module also touches os.environ
                # somewhere, so a mention of the token name elsewhere (e.g. a comment string) can't
                # falsely tag a script that never reads it.
                info.data_keys.add(node.value)

        if not uses_os_environ:
            info.data_keys -= set(DIRECT_SECRET_NAMES)

        infos.append(info)

    return infos


def cluster_for(stem):
    lower = stem.lower()
    for keyword, cluster_id, title in CLUSTER_RULES:
        if keyword in lower:
            return cluster_id, title
    return None, None


def build_mermaid(scripts):
    lines = ["```mermaid", "flowchart LR"]
    lines.append('    classDef script fill:#1f6feb,color:#ffffff,stroke:#0b3d91,stroke-width:1px;')
    lines.append('    classDef hub fill:#8250df,color:#ffffff,stroke:#4b1a91,stroke-width:2px;')
    lines.append('    classDef data fill:#f2cc60,color:#222222,stroke:#946200,stroke-width:1px;')
    lines.append("")

    # group scripts by cluster (None cluster = ungrouped, emitted last, outside any subgraph)
    clustered = {}
    ungrouped = []
    for s in scripts:
        cid, title = cluster_for(s.stem)
        if cid:
            clustered.setdefault(cid, (title, []))[1].append(s)
        else:
            ungrouped.append(s)

    script_ids = []
    hub_ids = []
    for cid in sorted(clustered):
        title, members = clustered[cid]
        lines.append(f'    subgraph {cid}["{title}"]')
        for s in sorted(members, key=lambda x: x.stem):
            label = s.stem + ".py"
            if s.external_tags:
                label += "<br/>(" + ",".join(sorted(s.external_tags)) + ")"
            lines.append(f'        {s.node_id}["{label}"]')
            script_ids.append(s.node_id)
        lines.append("    end")
        lines.append("")

    for s in sorted(ungrouped, key=lambda x: x.stem):
        label = s.stem + ".py"
        if s.external_tags:
            label += "<br/>(" + ",".join(sorted(s.external_tags)) + ")"
        lines.append(f'    {s.node_id}["{label}"]')
        if s.stem == "packenv":
            hub_ids.append(s.node_id)
        else:
            script_ids.append(s.node_id)
    lines.append("")

    # packenv data artifacts, boxed together
    all_artifacts = {}
    for s in scripts:
        for art_id, label in s.data_artifacts:
            all_artifacts[art_id] = label
    if all_artifacts:
        lines.append('    subgraph PACKENV_DATA["packenv.py data artifacts"]')
        for art_id in sorted(all_artifacts, key=lambda a: all_artifacts[a]):
            node_id = "D_" + sanitize_id(art_id)
            lines.append(f'        {node_id}[("{all_artifacts[art_id]}")]')
        lines.append("    end")
        lines.append("")

    by_stem = {s.stem: s for s in scripts}
    lines.append("    %% script -> script (imports)")
    edge_count_scripts = 0
    for s in sorted(scripts, key=lambda x: x.stem):
        for target_stem in sorted(s.local_imports):
            target = by_stem.get(target_stem)
            if target:
                lines.append(f"    {s.node_id} --> {target.node_id}")
                edge_count_scripts += 1
    lines.append("")

    lines.append("    %% script -> packenv data artifact (uses)")
    edge_count_data = 0
    for s in sorted(scripts, key=lambda x: x.stem):
        for art_id, _label in s.data_artifacts:
            node_id = "D_" + sanitize_id(art_id)
            lines.append(f"    {s.node_id} -.-> {node_id}")
            edge_count_data += 1
    lines.append("")

    if script_ids:
        lines.append("    class " + ",".join(script_ids) + " script;")
    if hub_ids:
        lines.append("    class " + ",".join(hub_ids) + " hub;")
    if all_artifacts:
        data_ids = ",".join("D_" + sanitize_id(a) for a in sorted(all_artifacts))
        lines.append("    class " + data_ids + " data;")

    lines.append("```")
    return "\n".join(lines), edge_count_scripts, edge_count_data, len(all_artifacts)


def build_table(scripts):
    header = "| Script | Purpose | Reads / uses (data artifacts) | Depends on (scripts) |"
    sep = "|---|---|---|---|"
    rows = [header, sep]
    for s in sorted(scripts, key=lambda x: x.stem.lower()):
        purpose = s.purpose.replace("|", "\\|")
        artifacts = ", ".join(label for _id, label in s.data_artifacts) or "—"
        deps = ", ".join(sorted(f"{d}.py" for d in s.local_imports)) or "—"
        tags = f" _[{','.join(sorted(s.external_tags))}]_" if s.external_tags else ""
        rows.append(f"| `{s.filename}` | {purpose}{tags} | {artifacts} | {deps} |")
    return "\n".join(rows)


def build_dot(scripts):
    lines = ["digraph arch {", '  rankdir=LR;', '  node [shape=box, style=filled, fontsize=10];', ""]
    all_artifacts = {}
    for s in scripts:
        for art_id, label in s.data_artifacts:
            all_artifacts[art_id] = label

    for s in sorted(scripts, key=lambda x: x.stem):
        color = "#8250df" if s.stem == "packenv" else "#1f6feb"
        fontcolor = "white"
        lines.append(
            f'  {s.node_id} [label="{s.stem}.py", fillcolor="{color}", fontcolor="{fontcolor}"];'
        )
    lines.append("")
    for art_id, label in sorted(all_artifacts.items(), key=lambda kv: kv[1]):
        node_id = "D_" + sanitize_id(art_id)
        lines.append(f'  {node_id} [label="{label}", shape=cylinder, fillcolor="#f2cc60"];')
    lines.append("")

    by_stem = {s.stem: s for s in scripts}
    for s in sorted(scripts, key=lambda x: x.stem):
        for target_stem in sorted(s.local_imports):
            target = by_stem.get(target_stem)
            if target:
                lines.append(f"  {s.node_id} -> {target.node_id};")
    for s in sorted(scripts, key=lambda x: x.stem):
        for art_id, _label in s.data_artifacts:
            node_id = "D_" + sanitize_id(art_id)
            lines.append(f"  {s.node_id} -> {node_id} [style=dashed];")
    lines.append("}")
    return "\n".join(lines) + "\n"


def build_markdown(scripts):
    mermaid, edges_scripts, edges_data, n_artifacts = build_mermaid(scripts)
    table = build_table(scripts)
    parse_errors = [s for s in scripts if s.parse_error]

    parts = [
        "# Cat-Pack-Utilities — Architecture / Data-Dependency Map",
        "",
        GENERATED_NOTE,
        "",
        f"{len(scripts)} scripts scanned · {edges_scripts} script→script import edges · "
        f"{edges_data} script→data-artifact edges · {n_artifacts} distinct packenv data artifacts.",
        "",
        "## Diagram",
        "",
        "Solid arrows = local `import`; dashed arrows = packenv (`E.<KEY>`) data-artifact use. "
        "The purple node is `packenv.py`, the hub every other script's paths/ids flow through.",
        "",
        mermaid,
        "",
        "## Overview table",
        "",
        table,
        "",
    ]
    if parse_errors:
        parts.append("## Scripts that could not be fully analyzed")
        parts.append("")
        for s in parse_errors:
            parts.append(f"- `{s.filename}`: {s.parse_error}")
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                     help="exit 1 if ARCHITECTURE.md is stale vs a freshly-generated version (no write)")
    ap.add_argument("--no-dot", action="store_true", help="skip writing ARCHITECTURE.dot")
    args = ap.parse_args()

    scripts = collect_scripts()
    md = build_markdown(scripts)

    if args.check:
        existing = None
        if os.path.isfile(OUTPUT_MD):
            with open(OUTPUT_MD, encoding="utf-8") as fh:
                existing = fh.read()
        if existing != md:
            print("ARCHITECTURE.md is STALE vs source — run `python3 arch_map.py` to regenerate.",
                  file=sys.stderr)
            sys.exit(1)
        print("ARCHITECTURE.md is up to date.")
        sys.exit(0)

    with open(OUTPUT_MD, "w", encoding="utf-8") as fh:
        fh.write(md)

    if not args.no_dot:
        with open(OUTPUT_DOT, "w", encoding="utf-8") as fh:
            fh.write(build_dot(scripts))

    n_edges_scripts = sum(len(s.local_imports) for s in scripts)
    n_edges_data = sum(len(s.data_artifacts) for s in scripts)
    print(f"Wrote {OUTPUT_MD} ({len(scripts)} scripts, {n_edges_scripts} import edges, "
          f"{n_edges_data} data-use edges).")
    if not args.no_dot:
        print(f"Wrote {OUTPUT_DOT}.")


if __name__ == "__main__":
    main()
