#!/usr/bin/env python3
"""matoulib_arch.py — auto-generates <repo>/ARCHITECTURE.md, a seam map of a matou mod source tree.

Why (2026-07-10): the matou 1.7.10 codebase was split into two repos — `matoulib-core` (the lib:
`-Dmatoulib.*` gate flags, `@`-DSL content sections, mixins, registries, RPC devtools) and `gigafauna`
(the content consumer: GigafaunaRpc endpoints, BrowserContent, content factories, @Mod proxy wiring).
Both are large Java mods whose shape nobody can see at a glance without grepping. This statically scans
every *.java under a repo's own `fr.iamacat.<namespace>` package (regex only — never compiles/imports)
and emits a high-signal seam map: feature-flag gate table, DSL-section table, registries, Content/Factory
entrypoints, mixin targets, RPC devtools endpoints, CommonProxy wiring order, and a package tree — plus a
package-level import graph (.dot). Mirrors the philosophy of `arch_map.py` (same dir): re-runnable, so the
map never goes stale — run it after adding/removing a flag, DSL section, mixin, or RPC endpoint.

Output goes into the scanned repo itself (`<repo>/ARCHITECTURE.md` + `.dot`), not this repo — that repo's
source is the thing being mapped. The repo checkout path is resolved by name from
`memory/repos.json` (`E.REPOS_JSON`, `path` field), never hardcoded.

Usage:
    python3 matoulib_arch.py                       # default --repo matoulib-core
    python3 matoulib_arch.py --repo gigafauna      # map the gigafauna consumer instead
    python3 matoulib_arch.py --repo matoulib-core --check  # exit 2 if that repo's map is stale (release gate)
"""
import argparse
import json
import os
import re
import sys

import packenv as E

# repo name (repos.json) -> the single `fr.iamacat.<namespace>` package that repo owns. Each repo also
# vendors a third-party API stub (cofh/api/energy) outside fr.iamacat, excluded by walking the namespace.
REPO_NAMESPACES = {
    "matoulib-core": "matoulib",
    "gigafauna": "gigafauna",
}
DEFAULT_REPO = "matoulib-core"

# Per-run globals, populated by configure() from the resolved --repo. Kept module-level so the scan
# helpers (JavaFile, collect_java_files, build_package_tree, main) can reference them unchanged.
REPO_NAME = None
REPO_DIR = None
SRC_ROOT = None
WALK_ROOT = None
ROOT_PACKAGE = None
OUTPUT_MD = None
OUTPUT_DOT = None


def resolve_repo_dir(repo_name):
    """Look up a repo's checkout dir by name in repos.json (path field). No hardcoded ~/GitHub paths."""
    with open(E.REPOS_JSON, encoding="utf-8") as fh:
        data = json.load(fh)
    for entry in data.get("repos", []):
        if entry.get("name") == repo_name:
            return os.path.expanduser(entry["path"])
    raise SystemExit(f"repo '{repo_name}' not found in {E.REPOS_JSON} (repos[].name).")


def configure(repo_name):
    global REPO_NAME, REPO_DIR, SRC_ROOT, WALK_ROOT, ROOT_PACKAGE, OUTPUT_MD, OUTPUT_DOT
    namespace = REPO_NAMESPACES[repo_name]
    REPO_NAME = repo_name
    REPO_DIR = resolve_repo_dir(repo_name)
    SRC_ROOT = os.path.join(REPO_DIR, "src", "main", "java")
    # Only the mod's own namespace is scanned — src/main/java also vendors a third-party API stub
    # (cofh/api/energy) outside fr.iamacat that is not this repo's source and would pollute the scan.
    WALK_ROOT = os.path.join(SRC_ROOT, "fr", "iamacat", namespace)
    ROOT_PACKAGE = f"fr.iamacat.{namespace}"
    OUTPUT_MD = os.path.join(REPO_DIR, "ARCHITECTURE.md")
    OUTPUT_DOT = os.path.join(REPO_DIR, "ARCHITECTURE.dot")


GENERATED_NOTE = (
    "> Auto-generated by `Cat-Pack-Utilities/matoulib_arch.py` from a static regex scan of "
    "`src/main/java` — do NOT hand-edit. Re-run `python3 matoulib_arch.py --repo <this-repo>` (in "
    "Cat-Pack-Utilities) after adding/removing a flag, DSL section, mixin, registry, or RPC endpoint. "
    "`--check` gates the release preflight."
)

FLAG_RE = re.compile(r'"(matoulib\.[A-Za-z0-9_.]+)"')
FLAG_READ_MARKERS = (
    # legacy direct JDK reads
    "Boolean.getBoolean", "Boolean.parseBoolean", "Integer.getInteger",
    "Long.getLong", "System.getProperty",
    # routed through fr.iamacat.matoulib.core.MatouFlags (2026-07-14 refactor: every direct JDK flag
    # read migrates to MatouFlags.<method>("matoulib.x") — same-line literal is still picked up by
    # FLAG_RE, this just widens which lines get scanned for it).
    "MatouFlags.bool(", "MatouFlags.i32(", "MatouFlags.i64(",
    "MatouFlags.f32(", "MatouFlags.f64(", "MatouFlags.str(", "MatouFlags.raw(",
)
CONST_DECL_RE = re.compile(r'\b\w*(?:FLAG|PROP)\w*\s*=\s*"(matoulib\.[A-Za-z0-9_.]+)"')
# In a *Flags.java holder every "matoulib.*" string const IS a flag, whatever the const is named
# (WorldgenFlags.OVERWORLD was invisible to CONST_DECL_RE, which requires FLAG|PROP in the name).
# MatouFlags.java itself is excluded from this (see extract_flags) — it's the resolver/router, not a
# holder of matoulib.* literal constants.
FLAGS_FILE_CONST_RE = re.compile(r'=\s*"(matoulib\.[A-Za-z0-9_.]+)"')

DSL_IMPL_RE = re.compile(r'\bclass\s+(\w+)\b[^{]*\bimplements\s+DslSection<\s*(\w+)\s*>')
DIRECTIVE_RE = re.compile(r'directive\s*\(\s*\)\s*\{.*?return\s*"([^"]+)"\s*;', re.S)

REGISTRY_RE = re.compile(r'\bclass\s+(\w*Registry)\b')
CONTENT_FACTORY_RE = re.compile(r'\bclass\s+(\w+(?:Content|Factory))\b')

MIXIN_ANNOT_RE = re.compile(r'@Mixin\s*\(([^)]*)\)', re.S)
MIXIN_TARGET_CLASS_RE = re.compile(r'(\w+)\.class')
MIXIN_TARGETS_STR_RE = re.compile(r'"([^"]+)"')
FIRST_CLASS_RE = re.compile(r'\bclass\s+(\w+)\b')

RPC_REGISTER_RE = re.compile(r'RpcServer\.register\s*\(\s*"([^"]+)"')

PROXY_CALL_RE = re.compile(r'\b([A-Z]\w*)\.(register|init|registerIfEnabled)\s*\(')
PROXY_METHODS = ("preInit", "init", "postInit")

IMPORT_RE = re.compile(r'^import\s+(fr\.iamacat(?:\.[A-Za-z0-9_]+)*)\s*;', re.M)


class JavaFile:
    def __init__(self, path):
        self.path = path
        self.rel = os.path.relpath(path, SRC_ROOT)
        self.rel_posix = self.rel.replace(os.sep, "/")
        pkg_dir = os.path.dirname(self.rel)
        self.package = pkg_dir.replace(os.sep, ".") if pkg_dir else ""
        stem = os.path.basename(path)[:-5]  # strip ".java"
        self.class_name = stem
        self.fqn = f"{self.package}.{stem}" if self.package else stem
        with open(path, encoding="utf-8") as fh:
            self.text = fh.read()


def collect_java_files():
    files = []
    for dirpath, _dirs, filenames in os.walk(WALK_ROOT):
        for name in sorted(filenames):
            if name.endswith(".java"):
                files.append(JavaFile(os.path.join(dirpath, name)))
    files.sort(key=lambda f: f.rel_posix)
    return files


def trim_package(pkg, max_parts=4):
    parts = pkg.split(".")
    return ".".join(parts[:max_parts])


# ── 1. feature flags ─────────────────────────────────────────────────────────────────────────────
def extract_flags(files):
    flag_files = {}  # flag -> set(rel_posix)
    for jf in files:
        if jf.class_name == "MatouFlags":
            # The flag *resolver* (fr.iamacat.matoulib.core.MatouFlags) — holds no matoulib.*
            # literals of its own (javadoc examples use unquoted {@code matoulib.x} form, which
            # FLAG_RE's quote requirement already ignores). Skip explicitly so it never gets
            # attributed as the "location" of every flag it merely routes reads through.
            continue
        for line in jf.text.splitlines():
            if any(marker in line for marker in FLAG_READ_MARKERS):
                for m in FLAG_RE.finditer(line):
                    flag_files.setdefault(m.group(1), set()).add(jf.rel_posix)
            for m in CONST_DECL_RE.finditer(line):
                flag_files.setdefault(m.group(1), set()).add(jf.rel_posix)
            if jf.rel_posix.endswith("Flags.java"):
                for m in FLAGS_FILE_CONST_RE.finditer(line):
                    flag_files.setdefault(m.group(1), set()).add(jf.rel_posix)
    return flag_files


# ── 2. DSL sections ──────────────────────────────────────────────────────────────────────────────
def extract_dsl_sections(files):
    rows = []  # (directive, def_type, fqn)
    for jf in files:
        m = DSL_IMPL_RE.search(jf.text)
        if not m:
            continue
        class_name, def_type = m.group(1), m.group(2)
        dm = DIRECTIVE_RE.search(jf.text)
        directive = dm.group(1) if dm else "(unresolved)"
        fqn = f"{jf.package}.{class_name}" if jf.package else class_name
        rows.append((directive, def_type, fqn))
    rows.sort(key=lambda r: r[0])
    return rows


# ── 3. registries ────────────────────────────────────────────────────────────────────────────────
def extract_registries(files):
    rows = []  # (class, package)
    for jf in files:
        for m in REGISTRY_RE.finditer(jf.text):
            rows.append((m.group(1), jf.package))
    rows = sorted(set(rows))
    return rows


# ── 4. Content/Factory entrypoints ───────────────────────────────────────────────────────────────
def extract_content_factory(files):
    rows = []  # (fqn, flag_or_dash)
    for jf in files:
        for m in CONTENT_FACTORY_RE.finditer(jf.text):
            class_name = m.group(1)
            fqn = f"{jf.package}.{class_name}" if jf.package else class_name
            fm = CONST_DECL_RE.search(jf.text)
            flag = fm.group(1) if fm else "—"
            rows.append((fqn, flag))
    rows = sorted(set(rows))
    return rows


# ── 5. mixins ────────────────────────────────────────────────────────────────────────────────────
def extract_mixins(files):
    rows = []  # (mixin_class, [targets])
    for jf in files:
        if "/mixins/" not in jf.rel_posix.replace("\\", "/") and ".mixins." not in jf.package:
            continue
        for annot in MIXIN_ANNOT_RE.finditer(jf.text):
            body = annot.group(1)
            targets = set(MIXIN_TARGET_CLASS_RE.findall(body))
            tm = re.search(r'targets\s*=\s*(\{[^}]*\}|"[^"]*")', body)
            if tm:
                targets.update(MIXIN_TARGETS_STR_RE.findall(tm.group(1)))
            cm = FIRST_CLASS_RE.search(jf.text)
            mixin_class = cm.group(1) if cm else jf.class_name
            rows.append((mixin_class, tuple(sorted(targets))))
    rows = sorted(set(rows))
    return rows


# ── 6. RPC devtools endpoints ────────────────────────────────────────────────────────────────────
def extract_rpc_endpoints(files):
    rows = {}  # path -> set(fqn)
    for jf in files:
        for m in RPC_REGISTER_RE.finditer(jf.text):
            rows.setdefault(m.group(1), set()).add(jf.fqn)
    return rows


# ── 7. CommonProxy wiring order ──────────────────────────────────────────────────────────────────
def find_matching_brace(text, open_brace_idx):
    depth = 0
    for i in range(open_brace_idx, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return -1


def extract_proxy_wiring(files):
    proxy = next((jf for jf in files if jf.class_name == "CommonProxy"), None)
    if proxy is None:
        return None, {}
    result = {}
    for method in PROXY_METHODS:
        sig_re = re.compile(rf'\bpublic\s+void\s+{method}\s*\([^)]*\)\s*\{{')
        m = sig_re.search(proxy.text)
        if not m:
            continue
        brace_start = proxy.text.index("{", m.start())
        brace_end = find_matching_brace(proxy.text, brace_start)
        if brace_end == -1:
            continue
        body = proxy.text[brace_start:brace_end]
        calls = [f"{cm.group(1)}.{cm.group(2)}()" for cm in PROXY_CALL_RE.finditer(body)]
        result[method] = calls
    return proxy, result


# ── 8. package tree ──────────────────────────────────────────────────────────────────────────────
def build_package_tree(files, max_depth=4):
    counts = {}  # package (dotted, relative to fr.iamacat) -> direct .java file count
    for jf in files:
        counts[jf.package] = counts.get(jf.package, 0) + 1

    children = {}  # parent pkg -> sorted set of immediate child pkgs
    all_pkgs = set(counts)
    for pkg in list(all_pkgs):
        parts = pkg.split(".")
        for i in range(1, len(parts)):
            all_pkgs.add(".".join(parts[:i]))
    for pkg in all_pkgs:
        parts = pkg.split(".")
        if len(parts) > 1:
            parent = ".".join(parts[:-1])
            children.setdefault(parent, set()).add(pkg)

    lines = []

    def render(pkg, depth, label):
        if depth > max_depth:
            return
        indent = "  " * depth
        n = counts.get(pkg, 0)
        suffix = f" ({n} .java)" if n else ""
        lines.append(f"{indent}{label}{suffix}")
        for child in sorted(children.get(pkg, ())):
            render(child, depth + 1, child.split(".")[-1])

    render(ROOT_PACKAGE, 0, ROOT_PACKAGE)
    return "\n".join(lines)


# ── .dot: package-level import graph ─────────────────────────────────────────────────────────────
def build_dot(files):
    edges = set()
    for jf in files:
        from_pkg = trim_package(jf.package)
        for m in IMPORT_RE.finditer(jf.text):
            imported_pkg = ".".join(m.group(1).split(".")[:-1])  # drop the imported class name
            if not imported_pkg.startswith("fr.iamacat"):
                continue
            to_pkg = trim_package(imported_pkg)
            if to_pkg and from_pkg and to_pkg != from_pkg:
                edges.add((from_pkg, to_pkg))

    nodes = sorted({p for e in edges for p in e})
    graph_name = re.sub(r"[^A-Za-z0-9_]", "_", f"{REPO_NAME}_arch") if REPO_NAME else "matoulib_arch"
    lines = [f"digraph {graph_name} {{", "  rankdir=LR;", "  node [shape=box, style=filled, fontsize=10, fillcolor=\"#1f6feb\", fontcolor=\"white\"];", ""]
    node_id = {p: "P_" + re.sub(r"[^A-Za-z0-9_]", "_", p) for p in nodes}
    # Distinguish packages the repo OWNS (internal, solid blue) from packages it merely IMPORTS
    # (external forward-edges — e.g. a consumer -> matoulib.*): the latter are boxed in a dashed
    # "external (imported)" cluster + greyed, so at a glance you read "what this repo IS" vs "what
    # it DEPENDS ON". A lib repo (ROOT_PACKAGE == fr.iamacat.matoulib) has no external node → no cluster.
    internal = [p for p in nodes if p.startswith(ROOT_PACKAGE)]
    external = [p for p in nodes if not p.startswith(ROOT_PACKAGE)]
    for p in internal:
        lines.append(f'  {node_id[p]} [label="{p}"];')
    if external:
        lines.append("")
        lines.append("  subgraph cluster_external {")
        lines.append('    label="external (imported, not owned by this repo)";')
        lines.append('    style=dashed; color="#999999"; fontcolor="#666666";')
        lines.append('    node [style="filled,dashed", fillcolor="#eaeef2", fontcolor="#24292f", color="#999999"];')
        for p in external:
            lines.append(f'    {node_id[p]} [label="{p}"];')
        lines.append("  }")
    lines.append("")
    for a, b in sorted(edges):
        lines.append(f"  {node_id[a]} -> {node_id[b]};")
    lines.append("}")
    return "\n".join(lines) + "\n", len(edges)


# ── markdown assembly ────────────────────────────────────────────────────────────────────────────
def build_markdown(files):
    flag_files = extract_flags(files)
    dsl_rows = extract_dsl_sections(files)
    registry_rows = extract_registries(files)
    cf_rows = extract_content_factory(files)
    mixin_rows = extract_mixins(files)
    rpc_rows = extract_rpc_endpoints(files)
    proxy_file, proxy_wiring = extract_proxy_wiring(files)
    pkg_tree = build_package_tree(files)
    _dot_text, dot_edges = build_dot(files)

    parts = [
        f"# {REPO_NAME} — architecture map "
        "(AUTO-GENERATED by Cat-Pack-Utilities/matoulib_arch.py — DO NOT edit by hand)",
        "",
        GENERATED_NOTE,
        "",
        f"{len(files)} .java files scanned · {len(flag_files)} `-Dmatoulib.*` flags · "
        f"{len(dsl_rows)} DSL sections · {len(registry_rows)} registries · {len(cf_rows)} "
        f"Content/Factory entrypoints · {len(mixin_rows)} mixins · {len(rpc_rows)} RPC endpoints · "
        f"{dot_edges} cross-package import edges.",
        "",
        "## 1. Feature flags (`-Dmatoulib.*` gate map)",
        "",
        "| Flag | File(s) that read/declare it |",
        "|---|---|",
    ]
    for flag in sorted(flag_files):
        files_str = ", ".join(f"`{f}`" for f in sorted(flag_files[flag]))
        parts.append(f"| `{flag}` | {files_str} |")

    parts += [
        "",
        "## 2. DSL sections (`@`-DSL directives)",
        "",
        "| Directive | Definition type | Class |",
        "|---|---|---|",
    ]
    for directive, def_type, fqn in dsl_rows:
        parts.append(f"| `{directive}` | `{def_type}` | `{fqn}` |")

    parts += [
        "",
        "## 3. Registries",
        "",
        "| Registry | Package |",
        "|---|---|",
    ]
    for class_name, package in registry_rows:
        parts.append(f"| `{class_name}` | `{package}` |")

    parts += [
        "",
        "## 4. Content / Factory entrypoints",
        "",
        "| Class | Gated by flag |",
        "|---|---|",
    ]
    for fqn, flag in cf_rows:
        flag_cell = flag if flag == "—" else f"`{flag}`"
        parts.append(f"| `{fqn}` | {flag_cell} |")

    parts += [
        "",
        "## 5. Mixins",
        "",
        "| Mixin class | Target(s) |",
        "|---|---|",
    ]
    for mixin_class, targets in mixin_rows:
        targets_str = ", ".join(f"`{t}`" for t in targets) or "—"
        parts.append(f"| `{mixin_class}` | {targets_str} |")

    parts += [
        "",
        "## 6. RPC devtools endpoints",
        "",
        "| Path | Handler class(es) |",
        "|---|---|",
    ]
    for path in sorted(rpc_rows):
        handlers = ", ".join(f"`{h}`" for h in sorted(rpc_rows[path]))
        parts.append(f"| `{path}` | {handlers} |")

    parts += [
        "",
        "## 7. CommonProxy wiring order",
        "",
    ]
    if proxy_file is None:
        parts.append("_CommonProxy.java not found._")
    else:
        parts.append(f"Source: `{proxy_file.rel_posix}` (registration calls, in source order):")
        parts.append("")
        for method in PROXY_METHODS:
            calls = proxy_wiring.get(method)
            parts.append(f"**{method}()**")
            parts.append("")
            if calls:
                for i, call in enumerate(calls, 1):
                    parts.append(f"{i}. `{call}`")
            else:
                parts.append("_(no register/init calls found)_")
            parts.append("")

    parts += [
        f"## 8. Package tree (`{ROOT_PACKAGE}.*`, depth-capped)",
        "",
        "```",
        pkg_tree,
        "```",
        "",
    ]

    return "\n".join(parts).rstrip() + "\n"


def summary_line(files, md_written_path):
    flag_files = extract_flags(files)
    dsl_rows = extract_dsl_sections(files)
    mixin_rows = extract_mixins(files)
    rpc_rows = extract_rpc_endpoints(files)
    return (
        f"Wrote {md_written_path} ({len(files)} java files, {len(flag_files)} flags, "
        f"{len(dsl_rows)} dsl-sections, {len(mixin_rows)} mixins, {len(rpc_rows)} endpoints)."
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--repo", choices=sorted(REPO_NAMESPACES), default=DEFAULT_REPO,
                     help=f"which matou repo to map (default: {DEFAULT_REPO})")
    ap.add_argument("--check", action="store_true",
                     help="exit 2 if <repo>/ARCHITECTURE.md is stale vs source (no write)")
    ap.add_argument("--no-dot", action="store_true", help="skip writing ARCHITECTURE.dot")
    args = ap.parse_args()

    configure(args.repo)

    if not os.path.isdir(WALK_ROOT):
        print(f"{REPO_NAME} source not found at {WALK_ROOT} "
              f"(check repos.json path for '{REPO_NAME}').", file=sys.stderr)
        sys.exit(1)

    files = collect_java_files()
    md = build_markdown(files)
    dot, _edges = build_dot(files)

    if args.check:
        stale = []
        existing_md = None
        if os.path.isfile(OUTPUT_MD):
            with open(OUTPUT_MD, encoding="utf-8", newline="") as fh:
                existing_md = fh.read()
        if existing_md != md:
            stale.append("ARCHITECTURE.md")

        existing_dot = None
        if os.path.isfile(OUTPUT_DOT):
            with open(OUTPUT_DOT, encoding="utf-8", newline="") as fh:
                existing_dot = fh.read()
        if existing_dot != dot:
            stale.append("ARCHITECTURE.dot")

        if stale:
            print(f"{REPO_NAME}/{{{', '.join(stale)}}} STALE vs source — run "
                  f"`python3 matoulib_arch.py --repo {REPO_NAME}` to regenerate.", file=sys.stderr)
            sys.exit(2)
        print(f"{REPO_NAME}/ARCHITECTURE.md and .dot are up to date.")
        sys.exit(0)

    with open(OUTPUT_MD, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(md)

    if not args.no_dot:
        with open(OUTPUT_DOT, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(dot)

    print(summary_line(files, OUTPUT_MD))
    if not args.no_dot:
        print(f"Wrote {OUTPUT_DOT}.")


if __name__ == "__main__":
    main()
