#!/usr/bin/env python3
"""matoulib_arch.py — auto-generates matoulib/ARCHITECTURE.md, a seam map of the matoulib mod source.

Why (2026-07-10): matoulib is a large 1.7.10 Java mod (fr.iamacat.{gigafauna,matoulib}) with many
`-Dmatoulib.*` gate flags, `@`-DSL content sections, mixins, and RPC devtools endpoints — nobody can see
the shape at a glance without grepping. This statically scans every *.java under
matoulib/src/main/java with regexes (never compiles/imports anything) and emits a high-signal seam map:
feature-flag gate table, DSL-section table, registries, Content/Factory entrypoints, mixin targets, RPC
devtools endpoints, CommonProxy wiring order, and a package tree — plus a package-level import graph
(.dot). Mirrors the philosophy of `arch_map.py` (same dir): re-runnable, so the map never goes stale —
run it after adding/removing a flag, DSL section, mixin, or RPC endpoint.

Output goes into the matoulib repo itself (matoulib/ARCHITECTURE.md + .dot), not this repo — matoulib's
source is the thing being mapped. The matoulib checkout path is derived from packenv (`E.GITHUB_ROOT`),
never hardcoded.

Usage:
    python3 matoulib_arch.py            # write matoulib/ARCHITECTURE.md (+ .dot)
    python3 matoulib_arch.py --check    # exit 2 if ARCHITECTURE.md is stale vs source (release-preflight gate)
"""
import argparse
import os
import re
import sys

import packenv as E

MATOULIB_DIR = os.path.join(E.GITHUB_ROOT, "matoulib")
SRC_ROOT = os.path.join(MATOULIB_DIR, "src", "main", "java")
# Only the mod's own namespace is scanned — src/main/java also vendors a third-party API stub
# (cofh/api/energy) that is not matoulib source and would pollute the flag/mixin/DSL/tree scan.
WALK_ROOT = os.path.join(SRC_ROOT, "fr", "iamacat")
ROOT_PACKAGE = "fr.iamacat"
OUTPUT_MD = os.path.join(MATOULIB_DIR, "ARCHITECTURE.md")
OUTPUT_DOT = os.path.join(MATOULIB_DIR, "ARCHITECTURE.dot")

GENERATED_NOTE = (
    "> Auto-generated by `Cat-Pack-Utilities/matoulib_arch.py` from a static regex scan of "
    "`src/main/java` — do NOT hand-edit. Re-run `python3 matoulib_arch.py` (in Cat-Pack-Utilities) "
    "after adding/removing a flag, DSL section, mixin, registry, or RPC endpoint. "
    "`--check` gates the release preflight."
)

FLAG_RE = re.compile(r'"(matoulib\.[A-Za-z0-9_.]+)"')
FLAG_READ_MARKERS = (
    "Boolean.getBoolean", "Boolean.parseBoolean", "Integer.getInteger",
    "Long.getLong", "System.getProperty",
)
CONST_DECL_RE = re.compile(r'\b\w*(?:FLAG|PROP)\w*\s*=\s*"(matoulib\.[A-Za-z0-9_.]+)"')

DSL_IMPL_RE = re.compile(r'\bclass\s+(\w+)\b[^{]*\bimplements\s+DslSection<\s*(\w+)\s*>')
DIRECTIVE_RE = re.compile(r'directive\s*\(\s*\)\s*\{.*?return\s*"([^"]+)"\s*;', re.S)

REGISTRY_RE = re.compile(r'\bclass\s+(\w*Registry)\b')
CONTENT_FACTORY_RE = re.compile(r'\bclass\s+(\w+(?:Content|Factory))\b')

MIXIN_ANNOT_RE = re.compile(r'@Mixin\s*\(([^)]*)\)', re.S)
MIXIN_TARGET_CLASS_RE = re.compile(r'(\w+)\.class')
MIXIN_TARGETS_STR_RE = re.compile(r'"([^"]+)"')
FIRST_CLASS_RE = re.compile(r'\bclass\s+(\w+)\b')

RPC_REGISTER_RE = re.compile(r'RpcServer\.register\s*\(\s*"([^"]+)"')

PROXY_CALL_RE = re.compile(r'\b([A-Z]\w*)\.(register|init|registerIfEnabled)\s*\(')
PROXY_METHODS = ("preInit", "init", "postInit")

IMPORT_RE = re.compile(r'^import\s+(fr\.iamacat(?:\.[A-Za-z0-9_]+)*)\s*;', re.M)


class JavaFile:
    def __init__(self, path):
        self.path = path
        self.rel = os.path.relpath(path, SRC_ROOT)
        self.rel_posix = self.rel.replace(os.sep, "/")
        pkg_dir = os.path.dirname(self.rel)
        self.package = pkg_dir.replace(os.sep, ".") if pkg_dir else ""
        stem = os.path.basename(path)[:-5]  # strip ".java"
        self.class_name = stem
        self.fqn = f"{self.package}.{stem}" if self.package else stem
        with open(path, encoding="utf-8") as fh:
            self.text = fh.read()


def collect_java_files():
    files = []
    for dirpath, _dirs, filenames in os.walk(WALK_ROOT):
        for name in sorted(filenames):
            if name.endswith(".java"):
                files.append(JavaFile(os.path.join(dirpath, name)))
    files.sort(key=lambda f: f.rel_posix)
    return files


def trim_package(pkg, max_parts=4):
    parts = pkg.split(".")
    return ".".join(parts[:max_parts])


# ── 1. feature flags ─────────────────────────────────────────────────────────────────────────────
def extract_flags(files):
    flag_files = {}  # flag -> set(rel_posix)
    for jf in files:
        for line in jf.text.splitlines():
            if any(marker in line for marker in FLAG_READ_MARKERS):
                for m in FLAG_RE.finditer(line):
                    flag_files.setdefault(m.group(1), set()).add(jf.rel_posix)
            for m in CONST_DECL_RE.finditer(line):
                flag_files.setdefault(m.group(1), set()).add(jf.rel_posix)
    return flag_files


# ── 2. DSL sections ──────────────────────────────────────────────────────────────────────────────
def extract_dsl_sections(files):
    rows = []  # (directive, def_type, fqn)
    for jf in files:
        m = DSL_IMPL_RE.search(jf.text)
        if not m:
            continue
        class_name, def_type = m.group(1), m.group(2)
        dm = DIRECTIVE_RE.search(jf.text)
        directive = dm.group(1) if dm else "(unresolved)"
        fqn = f"{jf.package}.{class_name}" if jf.package else class_name
        rows.append((directive, def_type, fqn))
    rows.sort(key=lambda r: r[0])
    return rows


# ── 3. registries ────────────────────────────────────────────────────────────────────────────────
def extract_registries(files):
    rows = []  # (class, package)
    for jf in files:
        for m in REGISTRY_RE.finditer(jf.text):
            rows.append((m.group(1), jf.package))
    rows = sorted(set(rows))
    return rows


# ── 4. Content/Factory entrypoints ───────────────────────────────────────────────────────────────
def extract_content_factory(files):
    rows = []  # (fqn, flag_or_dash)
    for jf in files:
        for m in CONTENT_FACTORY_RE.finditer(jf.text):
            class_name = m.group(1)
            fqn = f"{jf.package}.{class_name}" if jf.package else class_name
            fm = CONST_DECL_RE.search(jf.text)
            flag = fm.group(1) if fm else "—"
            rows.append((fqn, flag))
    rows = sorted(set(rows))
    return rows


# ── 5. mixins ────────────────────────────────────────────────────────────────────────────────────
def extract_mixins(files):
    rows = []  # (mixin_class, [targets])
    for jf in files:
        if "/mixins/" not in jf.rel_posix.replace("\\", "/") and ".mixins." not in jf.package:
            continue
        for annot in MIXIN_ANNOT_RE.finditer(jf.text):
            body = annot.group(1)
            targets = set(MIXIN_TARGET_CLASS_RE.findall(body))
            tm = re.search(r'targets\s*=\s*(\{[^}]*\}|"[^"]*")', body)
            if tm:
                targets.update(MIXIN_TARGETS_STR_RE.findall(tm.group(1)))
            cm = FIRST_CLASS_RE.search(jf.text)
            mixin_class = cm.group(1) if cm else jf.class_name
            rows.append((mixin_class, tuple(sorted(targets))))
    rows = sorted(set(rows))
    return rows


# ── 6. RPC devtools endpoints ────────────────────────────────────────────────────────────────────
def extract_rpc_endpoints(files):
    rows = {}  # path -> set(fqn)
    for jf in files:
        for m in RPC_REGISTER_RE.finditer(jf.text):
            rows.setdefault(m.group(1), set()).add(jf.fqn)
    return rows


# ── 7. CommonProxy wiring order ──────────────────────────────────────────────────────────────────
def find_matching_brace(text, open_brace_idx):
    depth = 0
    for i in range(open_brace_idx, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return -1


def extract_proxy_wiring(files):
    proxy = next((jf for jf in files if jf.class_name == "CommonProxy"), None)
    if proxy is None:
        return None, {}
    result = {}
    for method in PROXY_METHODS:
        sig_re = re.compile(rf'\bpublic\s+void\s+{method}\s*\([^)]*\)\s*\{{')
        m = sig_re.search(proxy.text)
        if not m:
            continue
        brace_start = proxy.text.index("{", m.start())
        brace_end = find_matching_brace(proxy.text, brace_start)
        if brace_end == -1:
            continue
        body = proxy.text[brace_start:brace_end]
        calls = [f"{cm.group(1)}.{cm.group(2)}()" for cm in PROXY_CALL_RE.finditer(body)]
        result[method] = calls
    return proxy, result


# ── 8. package tree ──────────────────────────────────────────────────────────────────────────────
def build_package_tree(files, max_depth=4):
    counts = {}  # package (dotted, relative to fr.iamacat) -> direct .java file count
    for jf in files:
        counts[jf.package] = counts.get(jf.package, 0) + 1

    children = {}  # parent pkg -> sorted set of immediate child pkgs
    all_pkgs = set(counts)
    for pkg in list(all_pkgs):
        parts = pkg.split(".")
        for i in range(1, len(parts)):
            all_pkgs.add(".".join(parts[:i]))
    for pkg in all_pkgs:
        parts = pkg.split(".")
        if len(parts) > 1:
            parent = ".".join(parts[:-1])
            children.setdefault(parent, set()).add(pkg)

    lines = []

    def render(pkg, depth, label):
        if depth > max_depth:
            return
        indent = "  " * depth
        n = counts.get(pkg, 0)
        suffix = f" ({n} .java)" if n else ""
        lines.append(f"{indent}{label}{suffix}")
        for child in sorted(children.get(pkg, ())):
            render(child, depth + 1, child.split(".")[-1])

    render(ROOT_PACKAGE, 0, ROOT_PACKAGE)
    return "\n".join(lines)


# ── .dot: package-level import graph ─────────────────────────────────────────────────────────────
def build_dot(files):
    edges = set()
    for jf in files:
        from_pkg = trim_package(jf.package)
        for m in IMPORT_RE.finditer(jf.text):
            imported_pkg = ".".join(m.group(1).split(".")[:-1])  # drop the imported class name
            if not imported_pkg.startswith("fr.iamacat"):
                continue
            to_pkg = trim_package(imported_pkg)
            if to_pkg and from_pkg and to_pkg != from_pkg:
                edges.add((from_pkg, to_pkg))

    nodes = sorted({p for e in edges for p in e})
    lines = ["digraph matoulib_arch {", "  rankdir=LR;", "  node [shape=box, style=filled, fontsize=10, fillcolor=\"#1f6feb\", fontcolor=\"white\"];", ""]
    node_id = {p: "P_" + re.sub(r"[^A-Za-z0-9_]", "_", p) for p in nodes}
    for p in nodes:
        lines.append(f'  {node_id[p]} [label="{p}"];')
    lines.append("")
    for a, b in sorted(edges):
        lines.append(f"  {node_id[a]} -> {node_id[b]};")
    lines.append("}")
    return "\n".join(lines) + "\n", len(edges)


# ── markdown assembly ────────────────────────────────────────────────────────────────────────────
def build_markdown(files):
    flag_files = extract_flags(files)
    dsl_rows = extract_dsl_sections(files)
    registry_rows = extract_registries(files)
    cf_rows = extract_content_factory(files)
    mixin_rows = extract_mixins(files)
    rpc_rows = extract_rpc_endpoints(files)
    proxy_file, proxy_wiring = extract_proxy_wiring(files)
    pkg_tree = build_package_tree(files)
    _dot_text, dot_edges = build_dot(files)

    parts = [
        "# matoulib — architecture map (AUTO-GENERATED by Cat-Pack-Utilities/matoulib_arch.py — DO NOT edit by hand)",
        "",
        GENERATED_NOTE,
        "",
        f"{len(files)} .java files scanned · {len(flag_files)} `-Dmatoulib.*` flags · "
        f"{len(dsl_rows)} DSL sections · {len(registry_rows)} registries · {len(cf_rows)} "
        f"Content/Factory entrypoints · {len(mixin_rows)} mixins · {len(rpc_rows)} RPC endpoints · "
        f"{dot_edges} cross-package import edges.",
        "",
        "## 1. Feature flags (`-Dmatoulib.*` gate map)",
        "",
        "| Flag | File(s) that read/declare it |",
        "|---|---|",
    ]
    for flag in sorted(flag_files):
        files_str = ", ".join(f"`{f}`" for f in sorted(flag_files[flag]))
        parts.append(f"| `{flag}` | {files_str} |")

    parts += [
        "",
        "## 2. DSL sections (`@`-DSL directives)",
        "",
        "| Directive | Definition type | Class |",
        "|---|---|---|",
    ]
    for directive, def_type, fqn in dsl_rows:
        parts.append(f"| `{directive}` | `{def_type}` | `{fqn}` |")

    parts += [
        "",
        "## 3. Registries",
        "",
        "| Registry | Package |",
        "|---|---|",
    ]
    for class_name, package in registry_rows:
        parts.append(f"| `{class_name}` | `{package}` |")

    parts += [
        "",
        "## 4. Content / Factory entrypoints",
        "",
        "| Class | Gated by flag |",
        "|---|---|",
    ]
    for fqn, flag in cf_rows:
        flag_cell = flag if flag == "—" else f"`{flag}`"
        parts.append(f"| `{fqn}` | {flag_cell} |")

    parts += [
        "",
        "## 5. Mixins",
        "",
        "| Mixin class | Target(s) |",
        "|---|---|",
    ]
    for mixin_class, targets in mixin_rows:
        targets_str = ", ".join(f"`{t}`" for t in targets) or "—"
        parts.append(f"| `{mixin_class}` | {targets_str} |")

    parts += [
        "",
        "## 6. RPC devtools endpoints",
        "",
        "| Path | Handler class(es) |",
        "|---|---|",
    ]
    for path in sorted(rpc_rows):
        handlers = ", ".join(f"`{h}`" for h in sorted(rpc_rows[path]))
        parts.append(f"| `{path}` | {handlers} |")

    parts += [
        "",
        "## 7. CommonProxy wiring order",
        "",
    ]
    if proxy_file is None:
        parts.append("_CommonProxy.java not found._")
    else:
        parts.append(f"Source: `{proxy_file.rel_posix}` (registration calls, in source order):")
        parts.append("")
        for method in PROXY_METHODS:
            calls = proxy_wiring.get(method)
            parts.append(f"**{method}()**")
            parts.append("")
            if calls:
                for i, call in enumerate(calls, 1):
                    parts.append(f"{i}. `{call}`")
            else:
                parts.append("_(no register/init calls found)_")
            parts.append("")

    parts += [
        "## 8. Package tree (`fr.iamacat.*`, depth-capped)",
        "",
        "```",
        pkg_tree,
        "```",
        "",
    ]

    return "\n".join(parts).rstrip() + "\n"


def summary_line(files, md_written_path):
    flag_files = extract_flags(files)
    dsl_rows = extract_dsl_sections(files)
    mixin_rows = extract_mixins(files)
    rpc_rows = extract_rpc_endpoints(files)
    return (
        f"Wrote {md_written_path} ({len(files)} java files, {len(flag_files)} flags, "
        f"{len(dsl_rows)} dsl-sections, {len(mixin_rows)} mixins, {len(rpc_rows)} endpoints)."
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                     help="exit 2 if matoulib/ARCHITECTURE.md is stale vs source (no write)")
    ap.add_argument("--no-dot", action="store_true", help="skip writing ARCHITECTURE.dot")
    args = ap.parse_args()

    if not os.path.isdir(SRC_ROOT):
        print(f"matoulib source not found at {SRC_ROOT} (check packenv.GITHUB_ROOT).", file=sys.stderr)
        sys.exit(1)

    files = collect_java_files()
    md = build_markdown(files)
    dot, _edges = build_dot(files)

    if args.check:
        stale = []
        existing_md = None
        if os.path.isfile(OUTPUT_MD):
            with open(OUTPUT_MD, encoding="utf-8", newline="") as fh:
                existing_md = fh.read()
        if existing_md != md:
            stale.append("ARCHITECTURE.md")

        existing_dot = None
        if os.path.isfile(OUTPUT_DOT):
            with open(OUTPUT_DOT, encoding="utf-8", newline="") as fh:
                existing_dot = fh.read()
        if existing_dot != dot:
            stale.append("ARCHITECTURE.dot")

        if stale:
            print(f"matoulib/{{{', '.join(stale)}}} STALE vs source — run "
                  "`python3 matoulib_arch.py` to regenerate.", file=sys.stderr)
            sys.exit(2)
        print("matoulib/ARCHITECTURE.md and .dot are up to date.")
        sys.exit(0)

    with open(OUTPUT_MD, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(md)

    if not args.no_dot:
        with open(OUTPUT_DOT, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(dot)

    print(summary_line(files, OUTPUT_MD))
    if not args.no_dot:
        print(f"Wrote {OUTPUT_DOT}.")


if __name__ == "__main__":
    main()
