#!/usr/bin/env python3
"""Scan ~/Documents/GitHub for repos owned by quentin452/iamacat and write the canonical
inventory to Mod-Sandbox/memory/repos.json — the SINGLE source of truth for "which forks/mods
do I own". The git remotes are the ground truth (a fork = has an `upstream` remote), so this
inventory is derived, never hand-maintained: no more duplicating the fork list across
pipeline-mods.md / release-manifest.json.

Usage:
  python3 scan_repos.py            # rewrite memory/repos.json
  python3 scan_repos.py --print    # print, don't write
"""
import json
import os
import subprocess
import sys

GITHUB_DIR = os.path.expanduser("~/Documents/GitHub")
OUT = os.path.expanduser("~/Documents/GitHub/Mod-Sandbox/memory/repos.json")
MANIFEST = os.path.expanduser("~/Documents/GitHub/Mod-Sandbox/memory/release-manifest.json")
OWNER_PAT = ("quentin452", "iamacat")

# is_fork is defined strictly as "has an `upstream` remote" — reproducible, and exactly what the
# staleness check (compare against upstream before fixing) needs. Conceptual forks without an
# `upstream` remote (e.g. a "reup" continuation) read as own; add the upstream remote to a repo if
# you want it treated as a fork.
FORK_OVERRIDE = {}


def git(repo, *args):
    r = subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else ""


def slug(url):
    if not url:
        return None
    u = url.removesuffix(".git")
    for pre in ("https://github.com/", "git@github.com:"):
        if u.startswith(pre):
            return u[len(pre):]
    return u


def main():
    manifest_repos = set()
    if os.path.exists(MANIFEST):
        for e in json.load(open(MANIFEST)).get("mods", []):
            manifest_repos.add(os.path.basename(os.path.expanduser(e.get("repo", "")).rstrip("/")))

    repos = []
    for name in sorted(os.listdir(GITHUB_DIR)):
        path = os.path.join(GITHUB_DIR, name)
        if not os.path.isdir(os.path.join(path, ".git")):
            continue
        origin = git(path, "remote", "get-url", "origin")
        if not any(o in origin.lower() for o in OWNER_PAT):
            continue
        upstream = git(path, "remote", "get-url", "upstream")
        is_fork = bool(upstream) or name in FORK_OVERRIDE
        # A gradle build present (most 1.7.10 mods use RFG/Forge gradle) — necessary but NOT
        # sufficient to be a MC mod (CatzEngine/binary-greedy-meshing have gradle but aren't mods).
        is_gradle = os.path.exists(os.path.join(path, "build.gradle")) or \
            os.path.exists(os.path.join(path, "build.gradle.kts")) or \
            os.path.exists(os.path.join(path, "gradle.properties"))
        # is_mod = ships an mcmod.info descriptor = the DEFINITIVE "this is a MC mod" marker. This
        # is what changelog/release tracking must filter on — a fork that is not a mod (rendering
        # engine, meshing lib) should never be flagged as an untracked pack mod. (BUG: track_audit
        # used is_fork and false-flagged CatzEngine/binary-greedy-meshing — 2026-07-07.)
        src = os.path.join(path, "src")
        is_mod = os.path.isdir(src) and any("mcmod.info" in fns for _, _, fns in os.walk(src))
        repos.append({
            "name": name,
            "path": f"~/Documents/GitHub/{name}",
            "slug": slug(origin),
            "upstream": slug(upstream) or FORK_OVERRIDE.get(name),
            "is_fork": is_fork,
            "branch": git(path, "branch", "--show-current"),
            "gradle": is_gradle,
            "is_mod": is_mod,
            "in_release_manifest": name in manifest_repos,
        })

    out = {
        "_comment": "AUTO-GENERATED by Cat-Pack-Utilities/scan_repos.py — DO NOT hand-edit the repo "
                    "list; it is derived from git remotes (the source of truth). Rerun the script "
                    "after cloning/adding a repo. is_fork = has an `upstream` remote (or FORK_OVERRIDE). "
                    "Release config (version/CF ids/targets) lives in release-manifest.json, not here.",
        "count": len(repos),
        "forks": sum(1 for r in repos if r["is_fork"]),
        "mods": sum(1 for r in repos if r.get("is_mod")),
        "repos": repos,
    }
    if "--print" in sys.argv:
        print(json.dumps(out, indent=2))
    else:
        json.dump(out, open(OUT, "w"), indent=2)
        print(f"wrote {OUT}: {out['count']} owned repos, {out['forks']} forks")


if __name__ == "__main__":
    main()
