#!/usr/bin/env python3
"""
track_audit.py — safety net for the "touch a mod/fork = track it in changelog-pending" rule.

Agents editing a mod are in the mod's worktree and CANNOT touch the hub, so their changelog-pending
entry is the orchestrator's job — easy to miss. This flags every OWNED mod (repos.json is_fork) that
has UNPUSHED commits but NO non-empty changelog-pending section = an untracked change.

  track_audit.py            # report untracked mods (exit 1 if any)

Run before wrapping a session / before a release, and after any agent edits a mod.
Note: relies on repos.json (auto-generated by scan_repos.py); a fork missing there is invisible.
"""
import json
import os
import re
import subprocess
import sys

HOME = os.path.expanduser("~")
HUB = os.path.join(HOME, "Documents/GitHub/Mod-Sandbox")
REPOS = os.path.join(HUB, "memory/repos.json")
CHANGELOG = os.path.join(HUB, "memory/changelog-pending.md")


def unpushed(repo):
    try:
        r = subprocess.run(["git", "-C", repo, "log", "--oneline", "@{u}.."],
                           capture_output=True, text=True, timeout=20)
        return [ln for ln in r.stdout.splitlines() if ln.strip()]
    except Exception:
        return []


def tracked_names():
    """Lowercased blob of every changelog-pending '## ...' section header that has a '* ' bullet."""
    if not os.path.exists(CHANGELOG):
        return ""
    txt = open(CHANGELOG, encoding="utf-8").read()
    out = []
    for part in re.split(r"^## ", txt, flags=re.M)[1:]:
        header = part.splitlines()[0] if part else ""
        body = "\n".join(part.splitlines()[1:])
        if re.search(r"^\* ", body, flags=re.M) and "(rien en attente)" not in body:
            out.append(header.lower())
    return " || ".join(out)


def main():
    if not os.path.exists(REPOS):
        sys.exit("repos.json not found (run scan_repos.py): " + REPOS)
    data = json.load(open(REPOS))
    repos = data.get("repos", data if isinstance(data, list) else [])
    tracked = tracked_names()

    flagged, checked = [], 0
    for r in repos:
        # owned = a fork (has upstream) — the set the tracking rule covers
        if not (r.get("is_fork") or r.get("upstream")):
            continue
        name = r.get("name", "")
        path = os.path.expanduser(r.get("path", ""))
        if not name or not os.path.isdir(path):
            continue
        checked += 1
        commits = unpushed(path)
        if not commits:
            continue
        # a section header mentioning the mod name (or its first token) = tracked
        key = name.lower()
        alt = key.split("-")[0].split("/")[0]
        if key in tracked or (len(alt) > 3 and alt in tracked):
            continue
        flagged.append((name, len(commits), commits[0]))

    if flagged:
        print(f"UNTRACKED mod changes ({len(flagged)} of {checked} owned repos with unpushed commits):")
        for name, n, top in flagged:
            print(f"  {name}: {n} unpushed commit(s), e.g. {top}")
        print("\n-> add a changelog-pending entry per the CLAUDE.md tracking rule (English), then re-run.")
        sys.exit(1)
    print(f"OK: all {checked} owned repos with unpushed commits have a changelog-pending entry.")


if __name__ == "__main__":
    main()
