#!/usr/bin/env python3
"""vanilla_import_map.py — auto-generates <repo>/VANILLA-IMPORTS.md, the engine-exit prioritisation map.

The docs/107 roadmap sequences the total-conversion by SUBSYSTEM narrative (render / net / entity / world).
That hides the one number that actually prioritises the work: HOW MANY vanilla/FML symbols each subsystem
still couples to, and WHERE. This statically scans `src/main/java/fr/iamacat/<namespace>` for every
`import net.minecraft* | net.minecraftforge* | cpw.mods.fml*` line and emits a ranked map:

  - per matou package: import count + file count (the adapter-surface ledger, the live twin of
    import-budgets.txt which is prose)
  - per vanilla subsystem (world / client / entity / item / block / nbt / network / fml-lifecycle ...):
    the total coupling, tagged with the doc that OWNS it, the roadmap stage that sheds it, and whether it
    is PLANCHER (irreducible host floor, docs/107 §0.2 — kept forever), ADAPTER (bridge by construction —
    devtools/mixins, excluded from the 0-target), or REDUCIBLE (the real conversion surface → 0).
  - per concrete vanilla symbol: the files that depend on it, so "replace World first" turns into a
    click-through worklist.

Output goes into the scanned repo itself (`<repo>/VANILLA-IMPORTS.md`), not this repo — that repo's source
is the thing being mapped. The repo checkout path is resolved by name from `memory/repos.json`
(`E.REPOS_JSON`, `path` field), never hardcoded. Sibling of `matoulib_arch.py`; same conventions.

Usage:
    python3 vanilla_import_map.py                        # default --repo matoulib-core
    python3 vanilla_import_map.py --repo gigafauna       # map the gigafauna consumer instead
    python3 vanilla_import_map.py --repo matoulib-core --check  # exit 2 if the map is stale (release gate)
"""
import argparse
import collections
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import packenv as E  # noqa: E402  (path-injected sibling, same as matoulib_arch)

REPO_NAMESPACES = {
    "matoulib-core": "matoulib",
    "gigafauna": "gigafauna",
}
DEFAULT_REPO = "matoulib-core"

# Per-run globals populated by configure().
REPO_NAME = None
REPO_DIR = None
WALK_ROOT = None
OUTPUT_MD = None

IMPORT_RE = re.compile(r'^\s*import\s+((?:net\.minecraft\w*|net\.minecraftforge|cpw\.mods\.fml)[\w.]+)\s*;')
# Inline FQN references (the "MC-free by FQN" pattern): fully-qualified vanilla/FML usages in CODE, which carry
# the exact same coupling as an import line but were invisible to the import-line scan (and to the gradle import
# ratchet). Counted separately, comments stripped first, import lines excluded.
FQN_RE = re.compile(r'\b((?:net\.minecraft\w*|net\.minecraftforge|cpw\.mods\.fml)(?:\.\w+)+)')
BLOCK_COMMENT_RE = re.compile(r'/\*.*?\*/', re.S)


def class_of(fqn):
    """Trim a matched dotted chain to its CLASS: keep segments up to and including the first Uppercase one
    (net.minecraft.entity.EntityList.createEntityByName -> net.minecraft.entity.EntityList). A chain with no
    uppercase segment (a bare package prefix) is returned whole — vns_group buckets it the same way."""
    out = []
    for part in fqn.split('.'):
        out.append(part)
        if part[:1].isupper():
            break
    return '.'.join(out)

GENERATED_NOTE = (
    "> Auto-generated by `Cat-Pack-Utilities/vanilla_import_map.py` from a static scan of "
    "`src/main/java` — do NOT hand-edit. Re-run `python3 vanilla_import_map.py --repo <this-repo>` after any "
    "change to the vanilla/FML import surface (owning a subsystem, porting a symbol to a MC-free twin, adding "
    "adapter code). `--check` gates the release preflight; it is the live twin of `import-budgets.txt`. "
    "Counts BOTH `import` lines AND inline FQN references (the \"MC-free by FQN\" pattern carries the same "
    "coupling — v2 2026-07-24; the gradle import ratchet still counts import lines only, see docs/104 §2.2)."
)

# ── Editorial classification: vanilla subsystem → (tier, owning doc, roadmap stage, note) ──────────────
# The COUNTS are computed; this table is the human prioritisation layer. `group` keys are the coarse
# vanilla namespace produced by vns_group(). Keep in sync with docs/46 (coverage) + docs/107 (stages).
TIER_PLANCHER = "PLANCHER"   # irreducible host floor (docs/107 §0.2) — kept forever
TIER_REDUCIBLE = "REDUCIBLE"  # the real conversion surface → 0 as ownership lands
TIER_MIXED = "MIXED"          # part host-anchor, part sheddable

# Symbol-level overrides — applied BEFORE the coarse vns_group() bucketing. The raw "fml(lifecycle)" and
# "entity" buckets over-count the irreducible floor (fable scope 2026-07-21, docs/104 §2.1 + 112): @Side/@SideOnly
# are NOT host-floor (core is unsided), GameRegistry dies at S7, the fml-network family → MatouChannel at S2, and
# EntityPlayer(MP) is a THIN anchor (docs/112 §3) that sheds most uses at S5 — NOT a mob-like S6 regime-c symbol.
SYMBOL_OVERRIDE = {
    "cpw.mods.fml.relauncher.Side": "fml(sided-annot)",
    "cpw.mods.fml.relauncher.SideOnly": "fml(sided-annot)",
    "cpw.mods.fml.common.registry.GameRegistry": "fml(registry)",
    "net.minecraft.entity.player.EntityPlayer": "player(anchor)",
    "net.minecraft.entity.player.EntityPlayerMP": "player(anchor)",
    "net.minecraft.entity.player.InventoryPlayer": "player(inventory)",
}
# Prefix overrides (checked after exact SYMBOL_OVERRIDE).
PREFIX_OVERRIDE = [
    ("cpw.mods.fml.common.network", "fml(net)"),
]

SUBSYSTEM_MAP = {
    "fml(lifecycle)": (TIER_MIXED, "107 §0.2 + 104 §2.3", "host floor / S5", "@Mod/proxies/lifecycle-events + FMLCommonHandler/SubscribeEvent/TickEvent (mostly → MatouClock/owned passes); true forever-floor ≈ a few dozen"),
    "fml(sided-annot)": (TIER_REDUCIBLE, "104 §2.1", "per-class port", "@Side/@SideOnly — the core is UNSIDED (sidedness is a host concept); NOT host floor"),
    "fml(registry)": (TIER_REDUCIBLE, "106", "S7 (Phase R)", "GameRegistry — content registration; dies at de-realization"),
    "fml(net)": (TIER_REDUCIBLE, "95 + 106-P3", "S2", "SimpleNetworkWrapper family → MatouChannel"),
    "player(anchor)": (TIER_MIXED, "112 §3", "S5 (lane AP/M) / anchor-forever", "EntityPlayer(MP) — thin anchor (connection identity + camera + input focus) kept; rest sheds at S5, NOT S6 regime-c"),
    "player(inventory)": (TIER_REDUCIBLE, "95 P2", "S7", "InventoryPlayer — container/inventory, ItemKey-first"),
    "world":          (TIER_REDUCIBLE, "105 + 70 + 46", "S3/S4/S6", "World/WorldServer/Chunk/EBS/biome — the SoA-world + storage-PRIMARY lever (biggest)"),
    "client(gui/render/input)": (TIER_REDUCIBLE, "64 + 124", "S1a/S8", "Minecraft/renderer/gui — render + gui ownership (mesher/gui partly done)"),
    "entity":         (TIER_REDUCIBLE, "71/72/80/92", "S6 (regime-c)", "Entity/EntityPlayer/LivingBase — blocks regime-c until entity-SoA replaces pos/motion fields"),
    "item":           (TIER_REDUCIBLE, "106 + S7", "S7", "content id surface — id-spine done (flag-off); de-realization is reader-gated"),
    "block":          (TIER_REDUCIBLE, "106 + S7", "S7", "content id surface — Block/Material; reader-gated de-realization"),
    "util":           (TIER_REDUCIBLE, "piecemeal", "any", "ResourceLocation/AABB/Vec3/IIcon/MathHelper — shed per-consumer (Mth ported)"),
    "nbt":            (TIER_REDUCIBLE, "94/95", "S2/S6", "save surface — player-only save; husk drops the rest"),
    "network":        (TIER_REDUCIBLE, "95 + 106-P3", "S2", "vanilla packets → MatouChannel"),
    "server":         (TIER_MIXED, "107 §0.2", "host floor / S5", "MinecraftServer anchor is PLANCHER; some uses shed with player-onto-sim"),
    "init":           (TIER_REDUCIBLE, "106", "S7", "Blocks/Items registries — content, reader-gated"),
    "tileentity":     (TIER_REDUCIBLE, "S7", "S7", "content tail"),
    "creativetab":    (TIER_REDUCIBLE, "S7", "S7", "content tail (menu)"),
    "inventory":      (TIER_REDUCIBLE, "104-D", "S7", "container/inventory — ItemKey first"),
    "potion":         (TIER_REDUCIBLE, "S7", "S7", "effects — de-realized before items"),
    "enchantment":    (TIER_REDUCIBLE, "S7", "S7", "content tail"),
    "pathfinding":    (TIER_REDUCIBLE, "78", "S6", "nav ownership"),
    "command":        (TIER_REDUCIBLE, "118", "S8", "own command surface (matoulib.command)"),
    "forge":          (TIER_MIXED, "—", "mixed", "Forge event bus (lifecycle-ish) + a few helpers"),
    "profiler":       (TIER_REDUCIBLE, "—", "any", "trivial"),
    "other":          (TIER_REDUCIBLE, "—", "?", "unclassified — inspect"),
}

# Adapter-tier matou packages: bridge by construction, excluded from the 0-import end-state (doc 104 §2.2).
ADAPTER_PACKAGES = {"devtools", "mixins"}

# ── Mixin lifecycle burn-down (hub doc 104 §1.4) ─────────────────────────────────────────────────────────
# Every @Mixin class carries a class-javadoc `Mixin lifecycle:` line with a machine `[retires=Sx|PERM]`
# token — the same source-of-truth the `checkMixinTags` gradle gate (matoulib-core build.gradle.kts)
# enforces. This just renders the burn-down; it does not fail the build (that is the gradle gate's job).
MIXIN_USE_RE = re.compile(r"@Mixin\b")
MIXIN_LIFECYCLE_RE = re.compile(r"Mixin lifecycle:.*?\b(TRANSITIONAL|PERMANENT)\b")
MIXIN_RETIRES_RE = re.compile(r"\[retires=(S[0-9][0-9a-z]*|PERM)\]")
STAGE_ORDER = ["S1a", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "PERM"]


def short_mixin_name(classname):
    return classname[len("Mixin"):] if classname.startswith("Mixin") else classname


def scan_mixins():
    """Walk WALK_ROOT/mixins for @Mixin classes. Return (rows, untagged):
    rows = sorted [(classname, kind, stage)] for every @Mixin class with a valid lifecycle tag;
    untagged = sorted [classname] for @Mixin classes missing the tag/token (should be empty in practice —
    the checkMixinTags gradle gate enforces this at build time). Absent `mixins` dir (other repos) -> ([], [])."""
    mixins_dir = os.path.join(WALK_ROOT, "mixins")
    if not os.path.isdir(mixins_dir):
        return [], []
    rows = []
    untagged = []
    for fn in sorted(os.listdir(mixins_dir)):
        if not fn.endswith(".java"):
            continue
        path = os.path.join(mixins_dir, fn)
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        if not MIXIN_USE_RE.search(text):
            continue
        classname = fn[: -len(".java")]
        m_kind = MIXIN_LIFECYCLE_RE.search(text)
        m_stage = MIXIN_RETIRES_RE.search(text)
        if m_kind and m_stage:
            rows.append((classname, m_kind.group(1), m_stage.group(1)))
        else:
            untagged.append(classname)
    rows.sort()
    untagged.sort()
    return rows, untagged


def vns_group(fqn):
    """Vanilla-subsystem bucket for a fully-qualified import (symbol overrides first, then coarse namespace)."""
    if fqn in SYMBOL_OVERRIDE:
        return SYMBOL_OVERRIDE[fqn]
    for prefix, group in PREFIX_OVERRIDE:
        if fqn.startswith(prefix):
            return group
    if fqn.startswith("cpw.mods.fml"):
        return "fml(lifecycle)"
    parts = fqn.split(".")
    if len(parts) >= 3 and parts[1] == "minecraft":
        x = parts[2]
        if x == "client":
            return "client(gui/render/input)"
        return x
    if len(parts) >= 2 and parts[1] == "minecraftforge":
        return "forge"
    return "other"


def resolve_repo_dir(repo_name):
    """Look up a repo's checkout dir by name in repos.json (path field). No hardcoded ~/GitHub paths."""
    with open(E.REPOS_JSON, encoding="utf-8") as fh:
        data = json.load(fh)
    for entry in data.get("repos", []):
        if entry.get("name") == repo_name:
            return os.path.expanduser(entry["path"])
    raise SystemExit(f"repo '{repo_name}' not found in {E.REPOS_JSON} (repos[].name).")


def configure(repo_name):
    global REPO_NAME, REPO_DIR, WALK_ROOT, OUTPUT_MD
    namespace = REPO_NAMESPACES[repo_name]
    REPO_NAME = repo_name
    REPO_DIR = resolve_repo_dir(repo_name)
    WALK_ROOT = os.path.join(REPO_DIR, "src", "main", "java", "fr", "iamacat", namespace)
    OUTPUT_MD = os.path.join(REPO_DIR, "VANILLA-IMPORTS.md")


def scan():
    """Walk WALK_ROOT, return aggregates over vanilla/FML coupling: import lines + inline FQN references."""
    pkg_imports = collections.Counter()          # matou 2nd-level pkg -> import lines
    pkg_inline = collections.Counter()            # matou 2nd-level pkg -> inline FQN refs
    pkg_files = collections.defaultdict(set)      # matou pkg -> {files with ANY coupling}
    sym_files = collections.defaultdict(set)      # vanilla class FQN -> {files} (imports + inline, unioned)
    group_imports = collections.Counter()         # vanilla subsystem -> import lines
    group_inline = collections.Counter()          # vanilla subsystem -> inline FQN refs
    group_pkgs = collections.defaultdict(set)     # vanilla subsystem -> {matou pkgs}
    total = 0
    total_inline = 0
    for dirpath, _, filenames in os.walk(WALK_ROOT):
        for fn in filenames:
            if not fn.endswith(".java"):
                continue
            path = os.path.join(dirpath, fn)
            rel = os.path.relpath(path, WALK_ROOT)
            pkg = rel.split(os.sep)[0] if os.sep in rel else "(top)"
            with open(path, encoding="utf-8", errors="replace") as fh:
                text = fh.read()
            # Strip comments/javadoc so doc mentions of vanilla names don't count as coupling. Line comments
            # are cut naively at // (a rare URL-in-string after it would be missed — acceptable).
            text = BLOCK_COMMENT_RE.sub("", text)
            for line in text.splitlines():
                m = IMPORT_RE.match(line)
                if m:
                    fqn = m.group(1)
                    total += 1
                    pkg_imports[pkg] += 1
                    pkg_files[pkg].add(rel)
                    sym_files[fqn].add(rel)
                    g = vns_group(fqn)
                    group_imports[g] += 1
                    group_pkgs[g].add(pkg)
                    continue
                code = line.split("//", 1)[0]
                for m in FQN_RE.finditer(code):
                    cls = class_of(m.group(1))
                    total_inline += 1
                    pkg_inline[pkg] += 1
                    pkg_files[pkg].add(rel)
                    sym_files[cls].add(rel)
                    g = vns_group(cls)
                    group_inline[g] += 1
                    group_pkgs[g].add(pkg)
    return dict(total=total, total_inline=total_inline, pkg_imports=pkg_imports, pkg_inline=pkg_inline,
               pkg_files=pkg_files, sym_files=sym_files, group_imports=group_imports,
               group_inline=group_inline, group_pkgs=group_pkgs)


def short_sym(fqn):
    return fqn.replace("net.minecraft.", "nm.").replace("net.minecraftforge.", "nmf.").replace("cpw.mods.fml.", "fml.")


def render_md(agg):
    L = []
    L.append(f"# Vanilla / FML import surface — `{REPO_NAME}`")
    L.append("")
    L.append(GENERATED_NOTE)
    L.append("")
    total = agg["total"]
    total_inline = agg["total_inline"]
    grand = total + total_inline
    adapter_total = sum(agg["pkg_imports"].get(p, 0) + agg["pkg_inline"].get(p, 0) for p in ADAPTER_PACKAGES)
    reducible_total = grand - adapter_total  # PLANCHER counted inside; noted per-subsystem below
    L.append(f"**Total vanilla/FML coupling:** {grand} ({total} `import` lines + {total_inline} inline FQN refs — "
             f"the \"MC-free by FQN\" pattern counts as coupling too)  ·  "
             f"**adapter-tier** (devtools+mixins, bridge by construction, off-target): {adapter_total}  ·  "
             f"**core+content+adapter-excluded reducible surface:** {reducible_total}")
    L.append("")
    L.append("Tiers: **PLANCHER** = irreducible host floor (docs/107 §0.2, kept forever) · "
             "**REDUCIBLE** = the real conversion surface (→ 0 as ownership lands) · "
             "**MIXED** = part anchor, part sheddable · **ADAPTER** = bridge packages, excluded from the 0-target.")
    L.append("")

    # ── Subsystem table (the prioritisation lever) ──
    L.append("## By vanilla subsystem — the ownership levers (ranked)")
    L.append("")
    L.append("| Vanilla subsystem | total | imports | inline | matou pkgs | tier | owns-it doc | sheds at | note |")
    L.append("|---|---:|---:|---:|---:|---|---|---|---|")
    combined = collections.Counter(agg["group_imports"])
    combined.update(agg["group_inline"])
    for g, count in combined.most_common():
        tier, doc, stage, note = SUBSYSTEM_MAP.get(g, (TIER_REDUCIBLE, "—", "?", "unclassified"))
        npk = len(agg["group_pkgs"][g])
        imp = agg["group_imports"].get(g, 0)
        inl = agg["group_inline"].get(g, 0)
        L.append(f"| {g} | {count} | {imp} | {inl} | {npk} | {tier} | {doc} | {stage} | {note} |")
    L.append("")

    # ── Per matou package (adapter-surface ledger) ──
    L.append("## By matou package — adapter-surface ledger (live twin of `import-budgets.txt`)")
    L.append("")
    L.append("| matou package | total | imports | inline | files | tier |")
    L.append("|---|---:|---:|---:|---:|---|")
    pkg_combined = collections.Counter(agg["pkg_imports"])
    pkg_combined.update(agg["pkg_inline"])
    for p, count in pkg_combined.most_common():
        tier = "ADAPTER" if p in ADAPTER_PACKAGES else "reducible/core"
        imp = agg["pkg_imports"].get(p, 0)
        inl = agg["pkg_inline"].get(p, 0)
        L.append(f"| {p} | {count} | {imp} | {inl} | {len(agg['pkg_files'][p])} | {tier} |")
    L.append("")

    # ── Mixin lifecycle burn-down (docs/104 §1.4) ──
    mixin_rows, mixin_untagged = scan_mixins()
    if mixin_rows or mixin_untagged:
        total_mixins = len(mixin_rows)
        by_stage = collections.defaultdict(list)
        for classname, _kind, stage in mixin_rows:
            by_stage[stage].append(classname)
        perm_count = len(by_stage.get("PERM", []))
        trans_count = total_mixins - perm_count

        present = set(by_stage)
        known = [s for s in STAGE_ORDER if s != "PERM" and s in present]
        unknown = sorted(s for s in present if s not in STAGE_ORDER)
        order = known + unknown + (["PERM"] if "PERM" in present else [])

        L.append("## Mixin lifecycle burn-down (docs/104 §1.4 — which mixins survive the husk)")
        L.append("")
        L.append(f"**End-state mixin floor (PERM only): {perm_count}** · peak (all {total_mixins} coexist "
                 f"during conversion) — the {trans_count} TRANSITIONAL fall as their stage lands. Render "
                 "mixins tagged S1a = docs/64 render lane (approximate; not husk-gated).")
        L.append("")
        if mixin_untagged:
            L.append(f"**WARNING: {len(mixin_untagged)} @Mixin file(s) missing a valid "
                     "`[retires=Sx|PERM]` lifecycle tag: " + ", ".join(mixin_untagged) +
                     " — regenerate after fixing (docs/104 §1.4).**")
            L.append("")
        L.append("| retires at | # mixins | cumulative alive-after | mixins |")
        L.append("|---|---:|---:|---|")
        cumulative_retired = 0
        for stage in order:
            names = sorted(by_stage.get(stage, []))
            count = len(names)
            if stage != "PERM":
                cumulative_retired += count
            alive_after = total_mixins - cumulative_retired
            short_names = ", ".join(short_mixin_name(n) for n in names)
            L.append(f"| {stage} | {count} | {alive_after} | {short_names} |")
        L.append("")

    # ── Top concrete symbols (the worklist) ──
    L.append("## Top vanilla symbols by coupling (files depending) — the concrete replace-worklist")
    L.append("")
    L.append("| files | vanilla symbol | subsystem |")
    L.append("|---:|---|---|")
    for fqn, files in sorted(agg["sym_files"].items(), key=lambda kv: (-len(kv[1]), kv[0]))[:40]:
        L.append(f"| {len(files)} | `{short_sym(fqn)}` | {vns_group(fqn)} |")
    L.append("")
    L.append("_The full per-symbol file map is intentionally not dumped here (hundreds of rows); grep the "
             "source for a symbol to get its exact call sites, or extend this script with a `--symbol` flag._")
    L.append("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Generate <repo>/VANILLA-IMPORTS.md (engine-exit import-surface map).")
    ap.add_argument("--repo", choices=sorted(REPO_NAMESPACES), default=DEFAULT_REPO,
                    help="which repo to map (resolved via repos.json). Default: matoulib-core.")
    ap.add_argument("--check", action="store_true",
                    help="exit 2 if <repo>/VANILLA-IMPORTS.md is stale vs source (no write)")
    args = ap.parse_args()

    configure(args.repo)
    if not os.path.isdir(WALK_ROOT):
        print(f"source root not found: {WALK_ROOT} (check repos.json path for '{REPO_NAME}').", file=sys.stderr)
        sys.exit(1)

    md = render_md(scan())

    if args.check:
        existing = ""
        if os.path.exists(OUTPUT_MD):
            with open(OUTPUT_MD, encoding="utf-8") as fh:
                existing = fh.read()
        if existing != md:
            print(f"{REPO_NAME}/VANILLA-IMPORTS.md STALE vs source — run "
                  f"`python3 vanilla_import_map.py --repo {REPO_NAME}`.", file=sys.stderr)
            sys.exit(2)
        print(f"{REPO_NAME}/VANILLA-IMPORTS.md up to date.")
        sys.exit(0)

    with open(OUTPUT_MD, "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"wrote {OUTPUT_MD}")


if __name__ == "__main__":
    main()
